Fix Unrecognized exception '$objectToArray errors
this error message shows up in the logs, when running with mongo 3.3: 
```
com.mongodb.MongoCommandException: Command failed with error 168 (InvalidPipelineOperator): 'Unrecognized expression '$objectToArray'' on server mongo:27017. The full response is {"ok": 0.0, "errmsg": "Unrecognized expression '$objectToArray'", "code": 168, "codeName": "InvalidPipelineOperator"}
```
Upgrading to mongo 3.4.23 fixes that. (same version as currently used in [the docker-compose on the microcks repo](https://github.com/microcks/microcks/blob/master/install/docker-compose/microcks.yml#L6) )