fix: cast result to string
`result` in this case can only be `string` as the
`FileReader.readAsText` is used in the code leading to `onload` callback
handler.

Fixes compile error:

```
ERROR in src/app/pages/apis/import/_components/import-form.component.ts:100:25 - error TS2322: Type 'string | ArrayBuffer' is not assignable to type 'string'.
  Type 'ArrayBuffer' is not assignable to type 'string'.

100                     let content: string = fileLoadedEvent.target["result"];
                            ~~~~~~~
```