fix: remove `moduleId` @Component property
This solves compile issue like:

```
RROR in src/app/app.component.ts:23:15 - error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

23     moduleId: module.id,
                 ~~~~~~
```