fix: import BrowserAnimationsModule
`ngx-bootstrap` depends on `BrowserAnimationsModule`, this fixes an
issue like:

```
ERROR NullInjectorError: R3InjectorError(e)[RU -> RU -> RU]:
  NullInjectorError: No provider for RU!
```

in the compiled JavaScript, or:

```
ERROR NullInjectorError: R3InjectorError(AppModule)[AnimationBuilder -> AnimationBuilder -> AnimationBuilder]:
  NullInjectorError: No provider for AnimationBuilder!
    Angular 9
    BsDropdownDirective_Factory ngx-bootstrap-dropdown.js:394
    Angular 4
    DropDownComponent_Template drop-down.component.html:1
    Angular 15
    CreateApiPageComponent_Template create.page.html:8
    Angular 22
    RxJS 5
    Angular 8
core.js:6210
```

with source maps present.